Using nvidia's mast-gather.sh
rh-ecosystem-edge/nvidia-ci pull request #48
Opened 2024-12-25 07:59 UTC by TomerNewman

We want to collect artifacts the same way as Nvidia does in their operator.
Now we download their must-gather script and uses it.

2025-01-08 10:48 UTC, empovit commented on internal/config/config.go
> +// GetDumpTestReportLocation returns destination file for tests logs.
IMO this can potentially hide a real issue. In a cloud environment, the artifacts directory is a mount. If the mount doesn't exist, this code `os.MkdirAll()` will just create a directory inside the test container, we will not see any error, but no artifacts will be collected. I think we better let any attempts to write to a non-existent artifacts directory fail. At most, we can create a sub-directory inside an already present artifacts directory.

2025-01-08 10:54 UTC, empovit commented on internal/config/config.go
> +// GetDumpTestReportLocation returns destination file for tests logs.
Also, why not to use `inittools.GeneralConfig.GetDumpFailedTestReportLocation()`? Which seems to have the same issue, BTW :)

2025-01-09 14:20 UTC, TomerNewman commented on internal/config/config.go
> +// GetDumpTestReportLocation returns destination file for tests logs.
1. Now instead of os.MkdirAll we will exit the function.
2. I meant inittools.GeneralConfig.GetDumpFailedReportLocation() probably, fixed

2025-01-13 15:41 UTC, TomerNewman commented
/test nvidia-gpu-operator-e2e-cutting-edge

2025-01-13 15:42 UTC, TomerNewman commented
/test 4.18-nvidia-gpu-operator-e2e-cutting-edge

2025-01-19 12:57 UTC, empovit requested changes

2025-01-19 12:57 UTC, empovit commented on Makefile
> +	test -s gpu-operator-must-gather.sh || (curl -SsL -o gpu-operator-must-gather.sh -L https://raw.githubusercontent.com/NVIDIA/gpu-operator/main/hack/must-gather.sh && chmod +x gpu-operator-must-gathe
I think it might make sense to check for errors as CodeRabbit is suggesting

2025-01-19 14:56 UTC, TomerNewman commented on scripts/test-runner.sh
> +chmod +x must-gather.sh
removing this section, we will download it from the Containerfile or makefile

2025-01-20 19:04 UTC, empovit commented on tests/nvidiagpu/gpu_suite_test.go
> +	if dumpDir != "" {
I think we want also 
```go
import (
    "github.com/onsi/ginkgo/v2/types"
)
```
...
```go
	if !types.SpecStateFailureStates.Is(CurrentSpecReport().State) {
		return
	}
```

to collect must-gather only in case of failure, just like `reporter.ReportIfFailed()`. 
Even better, we can create a reusable function to run a must-gather script if it was provided. E.g. `reporter.MustGatherIfFailed()`.
Let's address it in a new PR.

2025-01-20 19:06 UTC, empovit commented on tests/nvidiagpu/gpu_suite_test.go
> +			glog.Errorf("Error running gpu-operator-must-gather.sh script: %v\nOutput: %s", err, output)
If we extract this into a function, these must be either a generic message or a variable, e.g. `glot.Errorf("%s script timed out: %v", mustGatherScriptPath, ctx.Err()`

2025-01-20 19:07 UTC, empovit commented on tests/nvidiagpu/gpu_suite_test.go
> +		artifactDir := fmt.Sprintf("ARTIFACT_DIR=%s/gpu-must-gather", dumpDir)
In a generic function this would be a variable.

2025-01-20 19:08 UTC, empovit commented
/lgtm
/approve

2025-01-20 19:12 UTC, merged